import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header className='bg-white p-4 shadow-sm sticky top-0 z-10'>
        <div className='max-w-2xl mx-auto flex justify-between items-center'>
          <h1 className='text-xl font-bold text-gray-800'>SNSアプリ</h1>
          <div className='flex items-center space-x-4 scale-150'>
            <UserButton />
          </div>
        </div>
      </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
